#ifndef HAB_CONFIG_H
#define HAB_CONFIG_H

#define HAB_MAIN_TICK_HZ 1U

#define HAB_DEFAULT_TELEMETRY_PERIOD_S 5U
#define HAB_EVENT_TELEMETRY_PERIOD_S 1U
#define HAB_LOG_PERIOD_S 1U
#define HAB_LOG_FLUSH_INTERVAL_RECORDS 10U

#define HAB_GPS_ACQUIRE_TIMEOUT_S 60U
#define HAB_EVENT_MODE_DWELL_S 30U

#define HAB_ASCENT_CONFIRM_ALTITUDE_M 150.0f
#define HAB_ASCENT_CONFIRM_DWELL_S 30U
#define HAB_HIGH_ALTITUDE_TRIGGER_M 1000.0f
#define HAB_DESCENT_CONFIRM_DROP_M 100.0f

#define HAB_FLIGHT_IDLE_TO_ACTIVE_ALTITUDE_M 25.0f

#define HAB_ALTITUDE_FILTER_ALPHA 0.20f

#define HAB_LORA_PACKET_MAX_LEN 160U
#define HAB_SD_RECORD_MAX_LEN 224U

#endif
