#ifndef MSPM0_CCS_CONFIG_H
#define MSPM0_CCS_CONFIG_H

#define HAB_BME680_I2C_ADDRESS 0x76U

#define HAB_LORA_FREQUENCY_HZ 915000000UL
#define HAB_LORA_BANDWIDTH_ENUM 7U
#define HAB_LORA_SPREADING_FACTOR 9U
#define HAB_LORA_CODING_RATE 1U
#define HAB_LORA_PREAMBLE_SYMBOLS 8U
#define HAB_LORA_TX_POWER_DBM 17

#define HAB_SD_SPI_TIMEOUT_MS 100U
#define HAB_LORA_TX_TIMEOUT_MS 1500U

#endif
